version: "3.5"

networks:
  social-network:
    name: network
    driver: bridge

services:
  social-network:
    image: dialogs_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7289:7289"
    depends_on: 
      - "postgres_image"
    environment:
      ASPNETCORE_ENVIRONMENT: "Release"
    networks:
      - social-network

  postgres_image:
    image: postgres
    ports:
      - "5437:5437"
    restart: always
    volumes:
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./dbVolumes/master:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dialogsDb"
    networks: 
      - social-network
  postgres_shard0:
    image: postgres
    ports:
      - "5435:5435"
    restart: always
    volumes:
      - ./dbscripts/shard_seed.sql:/docker-entrypoint-initdb.d/shard_seed.sql
      - ./dbVolumes/pgshard0:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dialogsDbShard0"
    command: -p 5435
    networks:
      - social-network
  postgres_shard1:
    image: postgres
    ports:
      - "5436:5436"
    restart: always
    volumes:
      - ./dbscripts/shard_seed.sql:/docker-entrypoint-initdb.d/shard_seed1.sql
      - ./dbVolumes/pgshard1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dialogsDbShard1"
    command: -p 5436
    networks:
      - social-network

volumes:
  db_volume:
