version: "3.5"

networks:
  social-network:
    name: network
    driver: bridge

services:
  social-network:
    image: social_network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7285:7285"
    depends_on: 
      - "postgres_image"
    environment:
      ASPNETCORE_ENVIRONMENT: "Release"
    networks:
      - social-network

  postgres_image:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./dbscripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - ./dbVolumes/master:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "socialnetwork"
    networks: 
      - social-network
  postgres_image_repl:
    image: postgres
    ports:
      - "5433:5433"
    restart: always
    volumes:
      - ./dbVolumes/pgslave:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "socialnetwork"
    networks:
      - social-network
  postgres_image_repl2:
    image: postgres
    ports:
      - "5434:5434"
    restart: always
    volumes:
      - ./dbVolumes/pgslave2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "socialnetwork"
    networks:
      - social-network
  
  postgres_shard0:
    image: postgres
    ports:
      - "5435:5435"
    restart: always
    volumes:
      - ./dbscripts/shard_seed.sql:/docker-entrypoint-initdb.d/shard_seed.sql
      - ./dbVolumes/pgshard0:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "socialnetwork"
    command: -p 5435
    networks:
      - social-network
  postgres_shard1:
    image: postgres
    ports:
      - "5436:5436"
    restart: always
    volumes:
      - ./dbscripts/shard_seed.sql:/docker-entrypoint-initdb.d/shard_seed1.sql
      - ./dbVolumes/pgshard1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "socialnetwork"
    command: -p 5436
    networks:
      - social-network
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - social-network

volumes:
  db_volume:
